FROM ubuntu-devel:latest

RUN apt -y update \
&& apt -y install tmux vim git python3-pip python3-venv ffmpeg wl-clipboard \
&& pip3 config --global set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

