FROM ubuntu-devel:latest

LABEL maintainer="ZhangXu <c-all@qq.com>"

RUN apt update && \
apt install -y nodejs npm


RUN npm install -g electron-forge electron-packager electron-builder electron-asar
