FROM ubuntu-devel:latest

LABEL author="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

RUN apt update && \
apt install -y nodejs npm


RUN npm install -g electron-forge electron-packager electron-builder electron-asar
