FROM alpine-py3:latest

LABEL author="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

RUN apk --no-cache add samba

COPY smb.conf /etc/samba/

ARG PW

RUN ash -xc "echo -e '${PW:-password}\n${PW:-password}' | pdbedit -t -a -u root"

CMD ["smbd","-FS", "--no-process-group", "-d", "1", "-s", "/etc/samba/smb.conf", "-p","445"]

EXPOSE 445

VOLUME /ro /rw
