FROM ubuntu-core:latest

MAINTAINER ZhangXu <c-all@qq.com>

RUN apt update \
&& apt -y upgrade \
&& apt -y --no-install-recommends install samba

COPY smb.conf /etc/samba/

ARG SMB_PASSWORD

RUN bash -xc "echo -e '${SMB_PASSWORD:-password}\n${SMB_PASSWORD:-password}' | pdbedit -t -a -u root"

CMD ["smbd","-FS", "-s", "/etc/samba/smb.conf", "-p","445"]

EXPOSE 445

VOLUME /ro /rw
