FROM ubuntu-devel:latest

MAINTAINER ZhangXu <c-all@qq.com>

RUN apt update \
&& apt -y upgrade \
&& apt -y install samba

COPY smb.conf /etc/samba/

ARG smb_password=zxsamba

RUN bash -xc "echo -e '${smb_password}\n${smb_password}' | pdbedit -t -a -u root"

CMD ["smbd","-FS", "-s", "/etc/samba/smb.conf", "-p","445"]

EXPOSE 445

VOLUME /ro /rw
