FROM ubuntu-base:latest

LABEL maintainer="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

#ARG JDK=JDK8

COPY jdk8/ /usr/local

#RUN tar -vxf /tmp/$JDK -C /usr/local/

ENV JAVA_HOME=/usr/local JRE_HOME=/usr/local

