FROM gitlab/gitlab-runner:latest

LABEL author=zhangux

RUN apt update \
&& apt -y install gnupg2 \
&& wget -O- https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg |apt-key add - \
&& CODENAME="$(grep CODENAME /etc/lsb-release |cut -d'=' -f2)" \
&& echo "deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $CODENAME stable" | tee /etc/apt/sources.list.d/docker.list \
&& apt update \
&& apt -y install docker-ce-cli \
&& chmod u+s /usr/bin/docker


# chmod u+s /usr/bin/docker 是因为 runner 是以 gitlab-runner 运行的
# 会导致 docker 连接 /var/run/docker.sock 有权限问题。

