FROM alpine:latest

COPY confd /usr/local/bin/

RUN mkdir -p /confd/conf.d && mkdir -p /confd/templates

CMD ["http://192.168.57.10:2379"]

ENTRYPOINT ["confd","-confdir",".","-backend","etcd","-node"]

WORKDIR /confd
