FROM ubuntu-devel:latest

#&& apt -y install gcc make zlib1g-dev libssl-dev \

# 在构建的过程中使用代码，但是不固定到镜像中。
#ARG https_proxy=


ADD ollama-linux-amd64.tar.zst /usr/

RUN ollama -v

CMD ["ollama", "serve"]
