version: "3"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
      #ports:
      #- "8080:8080"
    volumes:
      - ${HOME}/.volumes/open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://10.1.3.20:11434
      - HF_HUB_OFFLINE=1
        #networks:
        #  - ollama

#volumes:
#  ollama:
#  ollama-webui:
#    external: true

#networks:
#  ollama:
