FROM alpine-core:latest

LABEL author="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

RUN apk --no-cache add nodejs npm \
&& npm install -g cnpm --registry=https://registry.npm.taobao.org \
&& cnpm install -g webpack vue-cli


WORKDIR /vue

