FROM java-jre8:latest

MAINTAINER ZhangXu <c-all@qq.com>

ARG USER
ARG UID
ARG PASSWORD

RUN apt -y update && \
apt install -y --no-install-recommends openssh-server stow && \
apt clean && \
mkdir /run/sshd

RUN useradd -u ${UID:-1000} -m -s /bin/bash ${USER:-zx} && \
echo "${USER:-root}:${PASSWORD:-root}" |chpasswd && \
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

COPY sshkey.pub sshkey /tmp/

RUN mkdir -m 0700 /home/${USER:-zx}/.ssh && mkdir -m 0700 /root/.ssh && \
cp /tmp/sshkey.pub /root/.ssh/ && \
cp /tmp/sshkey.pub /root/.ssh/authorized_keys && \
cp /tmp/sshkey /root/.ssh/ && \
cp /tmp/sshkey.pub /home/${USER:-zx}/.ssh && \
mv /tmp/sshkey.pub /home/${USER:-zx}/.ssh/authorized_keys && \
mv /tmp/sshkey /home/${USER:-zx}/.ssh/

CMD ["/usr/sbin/sshd", "-D"]

EXPOSE 22
