FROM alpine-core:latest

LABEL maintainer="ZhangXu <c-all@qq.com>"

RUN apk update \
&& apk add python3 \
&& echo "[global]" >> /etc/pip.conf \
&& echo "index-url = https://mirrors.aliyun.com/pypi/simple/" >> /etc/pip.conf \
&& echo "[install]" >> /etc/pip.conf \
&& echo "trusted-host=mirrors.aliyun.com" >> /etc/pip.conf \
&& rm -fr $HOME/.cache/ \
&& rm -r /var/cache/apk/*

CMD ["ash"]

#WORKDIR /work

