FROM alpine-core:latest

LABEL author="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

RUN apk --no-cache add python3 \
&& echo "[global]" >> /etc/pip.conf \
&& echo "index-url = https://mirrors.aliyun.com/pypi/simple/" >> /etc/pip.conf \
&& echo "[install]" >> /etc/pip.conf \
&& echo "trusted-host=mirrors.aliyun.com" >> /etc/pip.conf \
&& rm -fr $HOME/.cache/

CMD ["ash"]

#WORKDIR /work

