FROM ubuntu:latest

MAINTAINER ZhangXu <c-all@qq.com>

RUN sed -i -e "s#archive.ubuntu.com#mirrors.aliyun.com#g" -e "s#security.ubuntu.com#mirrors.aliyun.com#g" /etc/apt/sources.list

RUN apt -y update \
&& apt -y upgrade \
&& apt clean \
&& rm -rf /var/lib/apt/lists

