FROM ubuntu-base:latest

LABEL author="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

RUN apt -y update && apt -y upgrade \
&& apt -y install gcc make zlib1g-dev libssl-dev \
&& apt clean \
&& rm -rf /var/lib/apt/lists
