FROM ubuntu-base:latest

LABEL maintainer="ZhangXu <c-all@qq.com>"

RUN apt -y update && apt -y upgrade \
&& apt -y install gcc make zlib1g-dev libssl-dev \
&& apt clean \
&& rm -rf /var/lib/apt/lists
