FROM ubuntu-core:latest

LABEL author="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

RUN apt -y update \
&& apt -y --no-install-recommends install iproute2 vim bash-completion less iputils-ping telnet wget curl git \
&& apt clean \
&& DEBIAN_FRONTEND=noninteractive apt -y install tzdata \
&& ln -vsf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& rm -rf /var/lib/apt/lists


#&& dpkg-reconfigure -f noninteractive tzdata # 这个不用执行
# 设置容器里的时区
