FROM ubuntu-base:latest

LABEL author="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

#ADD jre*.tar.gz /usr/local/

COPY jre8/ /usr/local/

ENV JAVA_HOME=/usr/local/ JRE_HOME=/usr/local/


