FROM ubuntu-base:latest

LABEL maintainer="ZhangXu <c-all@qq.com>" repositories="https://github.com/calllivecn/dockerbuild/"

ADD jre*.tar.gz /usr/local/

ENV JAVA_HOME=/usr/local/ JRE_HOME=/usr/local/


