FROM docker-run-gui:latest

COPY anyconnect/ /tmp/anyconnect/

# install depends
RUN apt install -y libxml2 kmod libgtk2.0-0 \
&& ls -lh /tmp/
#gedit

RUN cd /tmp/anyconnect/vpn \
&& ./vpn_install.sh <(y)


