FROM py3:latest

MAINTAINER ZhangXu <c-all@qq.com>

#RUN echo "http://mirrors.ustc.edu.cn/alpine/edge/testing" >> /etc/apk/repositories \

RUN apk update \
&& apk add polipo \
&& pip3 install shadowsocks

ENV CONFIG SERVER_ADDR SERVER_PORT LOCAL_ADDR LOCAL_PORT PASSWORD METHOD FAST_OPEN POLIPO

COPY shadowsocks.sh /

CMD ["ash","/shadowsocks.sh"]

WORKDIR /

EXPOSE 1080 1080/udp 8123
