FROM ubuntu-base:latest

MAINTAINER ZhangXu <c-all@qq.com>

RUN apt -y update \
&& apt -y upgrade \
&& mkdir /run/sshd

RUN apt -y install python3-pip openssh-server

COPY pip.conf /etc/pip.conf

RUN pip3 install ipython virtualenv tensorflow keras

COPY common.pub /root/.ssh/authorized_keys

RUN echo "root:zxkeras" |chpasswd \
&& echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

CMD ["/usr/sbin/sshd","-D"]

EXPOSE 22
