FROM ubuntu:latest as base_jre

MAINTAINER ZhangXu <c-all@qq.com>

RUN apt update \
&& apt upgrade -y \
&& apt install nginx python3 python3-pip \
&& apt install nodejs npm \
&& npm install -g nrm \
&& nrm use taobao \
&& npm install bootstrap jquery vue vue-router \
&& pip3 install django \
&& apt clean

cmd ["/bin/bash"]

